<a class="btn btn-outline-primary btn-sm" href="/task/list" role="button"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> к списку задач</a>

<br><br>

<h3><?php echo $title; ?></h3>

<p>
	<span class="badge badge-light">
		<i class="fa fa-clock-o" aria-hidden="true"></i> создана  <?php echo $create; ?>
	</span>

	<?php if(!empty($closed)) : ?>
	<span class="badge badge-success">
		<i class="fa fa-clock-o" aria-hidden="true"></i> выполнена  <?php echo $closed; ?>
	</span>
	<?php endif ?>
	
	<?php if(!empty($user)) : ?>
	<span class="badge badge-light">
		<i class="fa fa-user-circle-o" aria-hidden="true"></i> <?php echo $user; ?>
	</span>
	<?php endif ?>
	
	<?php if(!empty($email)) : ?>
	<span class="badge badge-light">
		<i class="fa fa-envelope-o" aria-hidden="true"></i> <?php echo $email; ?>
	</span>
	<?php endif ?>

</p>


<?php if(!empty($img)) : ?>
<p>
	<img src="/img/<?= $img; ?>" class="img-thumbnail">
</p>
<?php endif ?>

<p><?php echo nl2br($content); ?></p>
